import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import Header from '@/component/header'
import Carousel from 'react-bootstrap/Carousel';
import Footer from '@/component/footer';
import { request, gql } from "graphql-request";
import { useQuery } from "react-query";

const endpoint = "http://localhost/wordpress/graphql/";
const FILMS_QUERY = gql`
  {
    posts {
      edges {
        node {
          title,content
        }
      }
    }
  }
`;
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data, isLoading, error } = useQuery("posts", () => {
    return request(endpoint, FILMS_QUERY);
  });
  console.log("data",data)
  if (isLoading) return "Loading...";
  if (error) return <pre>{error.message}</pre>;
  return (
    <>
      <Head>
        <title>MEIT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <div className="banner1">
    <Carousel>
      <Carousel.Item>
      <img typeof="foaf:Image" src="https://www.meity.gov.in/writereaddata/files/banner/3.-MeitY_0.png"  alt="Call for Application for the Global AI Expo" title="Call for Application for the Global AI Expo"/>
      
      </Carousel.Item>
      <Carousel.Item>
      <img typeof="foaf:Image" src="/images/juGajmc1gOVBUtt5.jpeg"  alt="Call for Application for the Global AI Expo" title="Call for Application for the Global AI Expo"/>
        
        
      </Carousel.Item>
      <Carousel.Item>
      <img typeof="foaf:Image" src="/images/Genesis Banner (MeitY Website).png"  alt="Call for Application for the Global AI Expo" title="Call for Application for the Global AI Expo"/>
      
      </Carousel.Item>
    </Carousel>
    </div>
    <h1>Posts</h1>
      <ul>
        {data.posts.edges.map((edge) => (
          <li key={edge.node.title}>
            <h3>{edge.node.title}</h3>
            <p>{edge.node.content}</p>
            </li>
        ))}
      </ul>
    <div className="about gap">
      <div className="container">
        <div className="row">
          <div className="col-md-6">
            <h3 className="heading">Our History</h3>
            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. </p>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>
          </div>
          <div className="col-md-6">
          <div class="image">
<img src="/images/news1.png" alt=""/>
</div>
          </div>
        </div>
      </div>
    </div>
    <div className="about mb-5">
      <div className="container">
        <div className="row align-items-center">
        <div className="col-md-6">
          <div class="image">
<img src="/images/about.png" alt=""/>
</div>
          </div>
          <div className="col-md-6">
            <h3 className="heading dash">We believe in the power of the media to change lives</h3>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.</p>
          </div>
          
        </div>
      </div>
    </div>
    <Footer/>
    </>
  )
}
